//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accgpa
    {
        public string REG_NO { get; set; }
        public string SEMESTER_NO { get; set; }
        public string CHAR_WORK { get; set; }
        public string SYN_INT { get; set; }
        public Nullable<decimal> Q_PREV { get; set; }
        public Nullable<decimal> Q_CURR_SEM { get; set; }
        public Nullable<decimal> Q_TOTAL { get; set; }
        public Nullable<decimal> CR_PREV { get; set; }
        public Nullable<decimal> CR_CURR_SEM { get; set; }
        public Nullable<decimal> CR_TOTAL { get; set; }
        public Nullable<decimal> CGPA { get; set; }
        public string USER_ID { get; set; }
        public string SECTION { get; set; }
        public string SEM_STATUS { get; set; }
        public Nullable<int> SemC { get; set; }
        public Nullable<int> dropCount { get; set; }
    
        public virtual SEMMTR SEMMTR { get; set; }
        public virtual STMTR STMTR { get; set; }
    }
}
