//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOCATE
    {
        public string EMP_NO { get; set; }
        public string COURSE_NO { get; set; }
        public string SEMESTER_NO { get; set; }
        public string SECTION { get; set; }
        public string DISCIPLINE { get; set; }
        public string SOS { get; set; }
        public string LEC1_DT { get; set; }
        public string LEC2_DT { get; set; }
        public string LEC3_DT { get; set; }
        public int SemC { get; set; }
    }
}
