//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRecord
    {
        public int RecordID { get; set; }
        public string Emp_no { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> DailyHours { get; set; }
        public string Comments { get; set; }
    }
}
