//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crsdtl
    {
        public string Course_no { get; set; }
        public string ATTEMPT_NO { get; set; }
        public string REG_NO { get; set; }
        public string Emp_no { get; set; }
        public string SEMESTER_NO { get; set; }
        public string SECTION { get; set; }
        public Nullable<decimal> Final_score { get; set; }
        public Nullable<decimal> Midterm_score { get; set; }
        public Nullable<decimal> Assi_score { get; set; }
        public Nullable<decimal> Prac_score { get; set; }
        public string Grade { get; set; }
        public Nullable<decimal> Q_points { get; set; }
        public string DISCIPLINE { get; set; }
        public string SOS { get; set; }
        public string pGrade { get; set; }
        public string Mid_att { get; set; }
        public string Fin_att { get; set; }
        public Nullable<int> CrsSemNo { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
    
        public virtual CRSMTR CRSMTR { get; set; }
        public virtual STMTR STMTR { get; set; }
        public virtual SEMMTR SEMMTR { get; set; }
    }
}
