//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRSMTR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRSMTR()
        {
            this.ClassReports = new HashSet<ClassReport>();
            this.Crsdtls = new HashSet<Crsdtl>();
        }
    
        public string Course_no { get; set; }
        public string Discipline { get; set; }
        public string Course_desc { get; set; }
        public string Credit_hrs { get; set; }
        public string Course_type { get; set; }
        public string SOS { get; set; }
        public string SOS_DESC { get; set; }
        public Nullable<int> ELective_course { get; set; }
        public string Old_SOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassReport> ClassReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crsdtl> Crsdtls { get; set; }
    }
}
