//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_In
    {
        public string User_name { get; set; }
        public string User_id { get; set; }
        public string User_type { get; set; }
        public string User_password { get; set; }
        public string MAC { get; set; }
        public string VID { get; set; }
        public string att { get; set; }
    }
}
