//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Teacher_Evaluation_SystemEntities2 : DbContext
    {
        public Teacher_Evaluation_SystemEntities2()
            : base("name=Teacher_Evaluation_SystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceRecord> AttendanceRecords { get; set; }
        public virtual DbSet<ClassReport> ClassReports { get; set; }
        public virtual DbSet<Crsdtl> Crsdtls { get; set; }
        public virtual DbSet<CRSMTR> CRSMTRs { get; set; }
        public virtual DbSet<Eval> Evals { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Question_Answer> Question_Answer { get; set; }
        public virtual DbSet<SEMMTR> SEMMTRs { get; set; }
        public virtual DbSet<STMTR> STMTRs { get; set; }
        public virtual DbSet<ALLOCATE> ALLOCATEs { get; set; }
        public virtual DbSet<EMPMTR> EMPMTRs { get; set; }
        public virtual DbSet<Log_In> Log_In { get; set; }
        public virtual DbSet<v_ClassHeldReport> v_ClassHeldReport { get; set; }
        public virtual DbSet<v_FullClassReport> v_FullClassReport { get; set; }
        public virtual DbSet<v_FullClassReport_Course> v_FullClassReport_Course { get; set; }
        public virtual DbSet<v_TeacherAttendance_EMPMTR> v_TeacherAttendance_EMPMTR { get; set; }
        public virtual DbSet<Accgpa> Accgpas { get; set; }
        public virtual DbSet<PeerEvaluation> PeerEvaluations { get; set; }
    }
}
