//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeerEvaluation
    {
        public int EvalID { get; set; }
        public string Evaluator_Emp_no { get; set; }
        public string Target_Emp_no { get; set; }
        public int Question_Desc { get; set; }
        public string Answer_Desc { get; set; }
        public Nullable<int> Answer_Marks { get; set; }
        public string Remarks { get; set; }
    }
}
