//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string reg_no { get; set; }
        public string sname { get; set; }
        public string @class { get; set; }
        public string semester_no { get; set; }
        public string supervisor { get; set; }
        public string grade { get; set; }
        public string project1 { get; set; }
        public string technology { get; set; }
        public string course_no { get; set; }
    }
}
