//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STMTR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STMTR()
        {
            this.Crsdtls = new HashSet<Crsdtl>();
            this.Accgpas = new HashSet<Accgpa>();
        }
    
        public string Reg_No { get; set; }
        public string App_no { get; set; }
        public string St_firstname { get; set; }
        public string St_lastname { get; set; }
        public string St_middlename { get; set; }
        public string Father_name { get; set; }
        public string St_email { get; set; }
        public string Sex { get; set; }
        public string Uaar_reg_no { get; set; }
        public string Marital_status { get; set; }
        public System.DateTime Birth_date { get; set; }
        public string Nic_no { get; set; }
        public string Ad_status { get; set; }
        public string Sess { get; set; }
        public string Pref_1 { get; set; }
        public string Pref_2 { get; set; }
        public Nullable<System.DateTime> Adm_date { get; set; }
        public string Semester_no { get; set; }
        public string Remarks { get; set; }
        public string St_status { get; set; }
        public string USER_ID { get; set; }
        public string Acc_status { get; set; }
        public string St_assets { get; set; }
        public string Whom_STATUS { get; set; }
        public string Fin_status { get; set; }
        public string Final_course { get; set; }
        public string Enrl_status { get; set; }
        public string DOMICILE { get; set; }
        public string Degree_Received { get; set; }
        public string Deg_No { get; set; }
        public string Year { get; set; }
        public string SOS { get; set; }
        public string Section { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crsdtl> Crsdtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accgpa> Accgpas { get; set; }
    }
}
