//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ClassHeldReport
    {
        public int SrNo { get; set; }
        public string Course { get; set; }
        public string Teacher { get; set; }
        public string Discipline_Section { get; set; }
        public string Venue { get; set; }
        public string Status { get; set; }
        public Nullable<int> Late_In { get; set; }
        public Nullable<int> Left_Early { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Emp_no { get; set; }
    }
}
